# Generated by Django 4.1 on 2022-09-01 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0005_auto_20220424_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("currency_title", models.CharField(max_length=64, verbose_name="Currency name")),
                ("currency_code", models.CharField(max_length=3, verbose_name="Currency code")),
            ],
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=64, verbose_name="Title")),
                (
                    "type_of_employment",
                    models.CharField(
                        choices=[("FT", "Full time"), ("PT", "Part time"), ("OT", "Other")],
                        db_index=True,
                        max_length=32,
                        verbose_name="Type of employment",
                    ),
                ),
                (
                    "location",
                    models.CharField(db_index=True, max_length=128, verbose_name="Location"),
                ),
                (
                    "english_level",
                    models.CharField(
                        choices=[
                            ("A0", "Unknown"),
                            ("A1", "Beginner"),
                            ("A2", "Elementary"),
                            ("B1", "Intermediate"),
                            ("B2", "Upper-intermediate"),
                            ("C1", "Advanced"),
                            ("C2", "Proficiency"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="English level",
                    ),
                ),
                (
                    "min_experience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0M", "Without experience"),
                            ("3M", "3 months experience"),
                            ("6M", "6 months experience"),
                            ("9M", "9 months experience"),
                            ("1Y", "1 year experience"),
                            ("1.5Y", "1,5 year experience"),
                            ("2Y", "2 years experience"),
                            ("3Y", "3 years experience"),
                            ("4Y", "4 years experience"),
                            ("5Y", "5 years experience"),
                        ],
                        db_index=True,
                        max_length=4,
                        verbose_name="Minimum experience in years",
                    ),
                ),
                ("end_date", models.DateField(verbose_name="Recruitment end date")),
                ("start_date", models.DateField(verbose_name="Recruitment start date")),
                ("description", models.TextField(max_length=2048, verbose_name="Description")),
                ("priority", models.TextField(max_length=512, verbose_name="Priority")),
                ("salary_max", models.IntegerField(db_index=True, verbose_name="Maximum salary")),
                ("salary_min", models.IntegerField(db_index=True, verbose_name="Minimum salary")),
                ("is_active", models.BooleanField(default=False, verbose_name="Is active")),
                (
                    "is_salary_show",
                    models.BooleanField(default=False, verbose_name="Is salary show"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="vacancy_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="vacancy_contact_person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "keywords",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "salary_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="vacancies.currency"
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
    ]
