# Generated by Django 4.1 on 2022-09-02 18:32


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="min_experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0M", "Without experience"),
                    ("3M", "3 months"),
                    ("6M", "6 months"),
                    ("9M", "9 months"),
                    ("1Y", "1 year"),
                    ("1.5Y", "1,5 year"),
                    ("2Y", "2 years"),
                    ("3Y", "3 years"),
                    ("4Y", "4 years"),
                    ("5Y", "5 years"),
                ],
                db_index=True,
                max_length=4,
                verbose_name="Minimum experience in years",
            ),
        ),
    ]
