# Generated by Django 4.1 on 2022-09-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("emails", "0001_initial"),
        ("emails", "0002_emailtemplate_author_alter_emailtemplate_body_and_more"),
    ]

    initial = True

    dependencies = [
        ("accounts", "0004_alter_user_groups_alter_user_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=255, verbose_name="Template name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("changed_at", models.DateTimeField(auto_now=True, verbose_name="Last updated")),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="HTML content (may contain template variables, read body docs).",
                        max_length=255,
                        null=True,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="HTML content (may contain template variables). You can use special codes that will be substituted with appropriate information. This template supports Candidates and Vacancies.<br/><br/><b>Candidates</b><br/>-----------<br/>{{cfullname}} stands for candidate's full name<br/>{{cname}} stands for candidate's firstname<br/>{{csurname}} stands for candidate's surname<br/>{{cage}} stands for candidate's age<br/><br/><b>Vacancy</b><br/>-----------<br/>{{vtitle}} stands for vacancy title<br/>{{vetype}} stands for vacancy employment type<br/>{{vlocation}} stands for vacancy location<br/>{{vel}} stands for vacancy level of english<br/>{{vme}} stands for minimal experience for vacancy<br/>{{vsd}} stands for vacancy start date<br/>{{ved}} stands for vacancy end date<br/>{{vdes}} stands for vacancy description<br/>{{vsalmin}} stands for vacancy minimal salary<br/>{{vsalmax}} stands for vacancy maximal salary<br/>{{vsalcur}} stands for vacancy salary currency<br/>-----------<br/><br/>You can use your own, which you can later add while sending emails.",
                        verbose_name="HTML template",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_templates",
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
    ]
