# Generated by Django 4.1 on 2022-09-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=255, verbose_name="Template name"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True, verbose_name="Created at")),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Last updated"),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="HTML content (may contain template variables, read body docs).",
                        max_length=255,
                        null=True,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="HTML content (may contain template variables). You can use special codes that will be substituted with appropriate information. This template supports Candidates and Vacancies.\nCandidates\n-----------\n{{cfullname}} stands for candidate's full name\n{{cname}} stands for candidate's firstname\n{{csurname}} stands for candidate's surname\n{{cage}} stands for candidate's age\nVacancy\n-----------\n{{vtitle}} stands for vacancy title\n{{vetype}} stands for vacancy employment type\n{{vlocation}} stands for vacancy location\n{{vel}} stands for vacancy level of english\n{{vme}} stands for vacancy minimal experience for vacancy\n{{vsd}} stands for vacancy start date\n{{ved}} stands for vacancy end date\n{{vdes}} stands for vacancy description\n{{vsalmin}} stands for vacancy minimal salary\n{{vsalmax}} stands for vacancy maximal salary\n{{vsalcur}} stands for vacancy salary currency\n-----------\nYou can use your own, which you can later add while sending emails.",
                        verbose_name="HTML template",
                    ),
                ),
            ],
        ),
    ]
