# Generated by Django 4.1 on 2022-09-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_groups_alter_user_is_superuser"),
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_templates",
                to="accounts.profile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="body",
            field=models.TextField(
                help_text="HTML content (may contain template variables). You can use special codes that will be substituted with appropriate information. This template supports Candidates and Vacancies.<br/><br/><b>Candidates</b><br/>-----------<br/>{{cfullname}} stands for candidate's full name<br/>{{cname}} stands for candidate's firstname<br/>{{csurname}} stands for candidate's surname<br/>{{cage}} stands for candidate's age<br/><br/><b>Vacancy</b><br/>-----------<br/>{{vtitle}} stands for vacancy title<br/>{{vetype}} stands for vacancy employment type<br/>{{vlocation}} stands for vacancy location<br/>{{vel}} stands for vacancy level of english<br/>{{vme}} stands for minimal experience for vacancy<br/>{{vsd}} stands for vacancy start date<br/>{{ved}} stands for vacancy end date<br/>{{vdes}} stands for vacancy description<br/>{{vsalmin}} stands for vacancy minimal salary<br/>{{vsalmax}} stands for vacancy maximal salary<br/>{{vsalcur}} stands for vacancy salary currency<br/>-----------<br/><br/>You can use your own, which you can later add while sending emails.",
                verbose_name="HTML template",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="changed_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last updated"),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
    ]
