# Generated by Django 4.1 on 2022-09-07 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "__first__"),
        ("events", "__first__"),
        ("candidates", "0001_initial"),
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="body",
            field=models.TextField(
                help_text="This template can support adding Event/Candidate/Vacancy info through usage of special tags. Just inserst a {{TAG_NAME}} in the template and it will be substituted for the appropriate info.<br/><br/><b><h3>Available tags:</h3><b><br/><b>Candidates<b>: name ({{candidate_name}}), surname ({{candidate_surname}}), full name ({{candidate_fullname}}), age ({{candidate_age}}).<br/><br/><b>Vacancies<b>: title ({{vacancy_title}}), type ({{vacancy_etype}}), location ({{vacancy_location}}), level of Englisg ({{vacancy_el}}), <br/>minimal experience ({{vacancy_me}}), start date ({{vacancy_sd}}), end date ({{vacancy_ed}}), description ({{vacancy_des}}), minimal salary ({{vacancy_salmin}}), <br/> maximal salary ({{vacancy_salmax}}), salary currency ({{vacancy_salcur}}).<br/><br/><b>Events<b>: title ({{event_title}}), description ({{event_description}}), type ({{event_type}}), start time ({{event_st}}),<br/> end time ({{event_et}}), duration ({{event_duration}}).",
                verbose_name="HTML template",
            ),
        ),
        migrations.CreateModel(
            name="EmailLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Letter Name")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Created"), (1, "In process"), (2, "Sent"), (3, "Failed")],
                        default=0,
                        verbose_name="Email Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("changed_at", models.DateTimeField(auto_now=True, verbose_name="Last updated")),
                ("sent_at", models.DateTimeField(null=True, verbose_name="Sent at")),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.event",
                        verbose_name="Associated Event",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(to="candidates.candidate", verbose_name="Recipients"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="emails.emailtemplate",
                        verbose_name="Template",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vacancies.vacancy",
                        verbose_name="Associated Vacancy",
                    ),
                ),
            ],
        ),
    ]
