# Generated by Django 4.1 on 2022-09-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_groups_alter_user_is_superuser"),
        ("emails", "0001_squashed_0002_emailtemplate_author_alter_emailtemplate_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_templates",
                to="accounts.profile",
            ),
        ),
    ]
