# Generated by Django 4.1 on 2022-09-07 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0001_initial"),
        ("events", "0001_initial"),
        ("emails", "0002_alter_emailtemplate_body_emailletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailletter",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="Associated Event",
            ),
        ),
        migrations.AlterField(
            model_name="emailletter",
            name="vacancy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vacancies.vacancy",
                verbose_name="Associated Vacancy",
            ),
        ),
    ]
