# Generated by Django 4.1 on 2022-09-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0001_initial"),
        ("candidates", "0002_candidate_vacancy"),
        ("events", "0001_initial"),
        ("emails", "0003_alter_emailletter_event_alter_emailletter_vacancy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailletter",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="letters",
                to="events.event",
                verbose_name="Associated Event",
            ),
        ),
        migrations.AlterField(
            model_name="emailletter",
            name="recipients",
            field=models.ManyToManyField(
                related_name="sent_letters", to="candidates.candidate", verbose_name="Recipients"
            ),
        ),
        migrations.AlterField(
            model_name="emailletter",
            name="vacancy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="letters",
                to="vacancies.vacancy",
                verbose_name="Associated Vacancy",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="body",
            field=models.TextField(
                help_text="This template can support adding Event/Candidate/Vacancy info through usage of special tags. Just inserst a {{TAG_NAME}} in the template and it will be substituted for the appropriate info.<br/><br/><b><h3>Available tags:</h3></b><br/><b>Candidates</b>: name ({{candidate_name}}), surname ({{candidate_surname}}), full name ({{candidate_fullname}}), age ({{candidate_age}}).<br/><br/><b>Vacancies</b>: title ({{vacancy_title}}), type ({{vacancy_etype}}), location ({{vacancy_location}}), level of Englisg ({{vacancy_el}}), <br/>minimal experience ({{vacancy_me}}), start date ({{vacancy_sd}}), end date ({{vacancy_ed}}), description ({{vacancy_des}}), minimal salary ({{vacancy_salmin}}), <br/> maximal salary ({{vacancy_salmax}}), salary currency ({{vacancy_salcur}}).<br/><br/><b>Events</b>: title ({{event_title}}), description ({{event_description}}), type ({{event_type}}), start time ({{event_st}}),<br/> end time ({{event_et}}), duration ({{event_duration}}).",
                verbose_name="HTML template",
            ),
        ),
    ]
