# Generated by Django 4.1 on 2022-09-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="duration",
            field=models.DurationField(
                blank=True, editable=False, null=True, verbose_name="End time"
            ),
        ),
    ]
