# Generated by Django 4.1 on 2022-09-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_groups_alter_user_is_superuser"),
        ("events", "0003_alter_event_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="duration",
            field=models.DurationField(
                blank=True, editable=False, null=True, verbose_name="Duration"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_time",
            field=models.DateTimeField(verbose_name="Event ends at"),
        ),
        migrations.AlterField(
            model_name="event",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_events",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_time",
            field=models.DateTimeField(verbose_name="Event starts at"),
        ),
    ]
