# Generated by Django 4.1 on 2022-09-05 15:53

import datetime
import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, verbose_name="Firstname")),
                ("surname", models.CharField(db_index=True, max_length=50, verbose_name="Surname")),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                        verbose_name="Birth date",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="O",
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_index=True,
                        max_length=128,
                        region=None,
                        unique=True,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=100, verbose_name="Email address"
                    ),
                ),
                (
                    "level_of_english",
                    models.CharField(
                        choices=[
                            ("A0", "Unknown"),
                            ("A1", "Beginner"),
                            ("A2", "Elementary"),
                            ("B1", "Intermediate"),
                            ("B2", "Upper-intermediate"),
                            ("C1", "Advanced"),
                            ("C2", "Proficiency"),
                        ],
                        default="A0",
                        max_length=2,
                        verbose_name="Level of English",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, max_length=1200, null=True, verbose_name="Additional info"
                    ),
                ),
                (
                    "additional_contacts",
                    models.TextField(
                        blank=True,
                        help_text="Here you can store additional contacts, like Skype.",
                        max_length=400,
                        null=True,
                        verbose_name="Additional contacts",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last update")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
            ],
            options={
                "ordering": ("surname", "name"),
            },
        ),
    ]
