# Generated by Django 4.1 on 2022-09-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0001_initial"),
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="vacancy",
            field=models.ManyToManyField(
                blank=True,
                related_name="vacancies",
                to="vacancies.vacancy",
                verbose_name="Vacancies",
            ),
        ),
    ]
