# Generated by Django 4.1 on 2022-08-24 19:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="additional_contacts",
            field=models.TextField(
                blank=True,
                help_text="Here you can store additional contacts, like Skype.",
                max_length=400,
                null=True,
                verbose_name="Additional contacts",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="level_of_english",
            field=models.CharField(
                choices=[
                    ("A0", "Unknown"),
                    ("A1", "Beginner"),
                    ("A2", "Elementary"),
                    ("B1", "Intermediate"),
                    ("B2", "Upper-intermediate"),
                    ("C1", "Advanced"),
                    ("C2", "Proficiency"),
                ],
                default="A0",
                max_length=2,
                verbose_name="Level of English",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="notes",
            field=models.TextField(
                blank=True, max_length=1200, null=True, verbose_name="Additional info"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True, max_length=128, region=None, unique=True, verbose_name="Phone number"
            ),
        ),
    ]
