# Generated by Django 4.1 on 2022-08-25 12:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_candidate_additional_contacts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(limit_value=datetime.date.today)
                ],
                verbose_name="Birth date",
            ),
        ),
    ]
