# Generated by Django 4.1 on 2022-09-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0002_alter_vacancy_min_experience"),
        ("candidates", "0003_alter_candidate_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="vacancy",
            field=models.ManyToManyField(
                blank=True, related_name="Vacancies", to="vacancies.vacancy"
            ),
        ),
    ]
