# Generated by Django 4.1 on 2022-09-07 08:20

from django.contrib.auth.models import Group
from django.db import migrations


def add_groups(apps, schema_editor):
    Group.objects.get_or_create(name="Recruiter")
    Group.objects.get_or_create(name="Reviewer")

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_groups),
    ]
